name: CD

on:
  push:
    branches:
      - main

env:
  HADOOP_USER_NAME: hive

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          server-id: github
          cache: 'maven'
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Prepare release
        run: |
          chmod +x mvnw
          ./mvnw clean install -DskipTests
      - name: Save version number in env
        run: |
          echo "VERSION=$(grep 'project.rel.org.alaturqua\\:trino-ai=' release.properties | cut -d'=' -f2)" >> $GITHUB_ENV
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: v${{ env.VERSION }}
          title: v${{ env.VERSION }}
          files: |
            target/*.zip
